build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "TBB/4.4.4"
    CONAN_USERNAME: "camposs"
    CONAN_LOGIN_USERNAME: "camposs"
    CONAN_CHANNEL: "stable"
    CONAN_STABLE_BRANCH_PATTERN: "stable/*"
    CONAN_UPLOAD: "https://conan.campar.in.tum.de"
    CONAN_UPLOAD_ONLY_WHEN_STABLE: 1

    matrix:
        - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix, 5@x86_64@seh@posix, 6@x86_64@seh@posix, 7@x86_64@seh@posix"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 12
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CONAN_VISUAL_VERSIONS: 14
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15


install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - cinst mingw
  - set PATH=C:\MinGW\bin;C:\tools\mingw64\bin;%PATH%
  - python build.py
